import type { Metadata } from 'next'
import { Baumans } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const baumas = Baumans({
    subsets: ['latin'],
    weight: '400',
    variable: '--font-baumas',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <Head>
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0"
                />
            </Head>
            <body className={`${baumas.className} `}>{children}</body>
        </html>
    )
}
